### ISSUE TITLE
longDescription in publiccode.yml is too short

### ISSUE THREAD

**Issue by bfabio** [INGV/dante#1]
`publiccode.yml` doesn't validate because `longDescription` is too short:

```
$ GET https://raw.githubusercontent.com/INGV/dante/master/publiccode.yml | docker run -i italia/publiccode-parser-go /dev/stdin
validation ko:
description/en/longDescription: too short (64), min 500 chars
```

**Comment by bfabio** [comment]
Hi @vlauciani, can we expand the long description someway?

**Comment by vlauciani** [comment]
Hi @bfabio 

Thank you for your issue... I've no updated the `publiccode.yml` because I need to remove/delete the project; I'm working on a new version and It will be released before the end of the year.

Valentino

**Comment by bfabio** [comment]
Thanks @vlauciani
